version: 2
jobs:
  build:
    docker:
      - image: mono
    steps:
      - checkout
      - run:
          name: xamarin
          command: cd /Library/Frameworks/Mono.framework/Commands/nuget
      - run:
          name: ls
          command: ls
          
