version: 2
jobs:
  build:
    docker:
      - image: java
    steps:
      - checkout
      - run: apt-get update
      - run: lsb_release –a
      - run:
          name: install
          command: apt-get install -y wget && wget https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/lastSuccessfulBuild/Azure/processDownloadRequest/xamarin-android/xamarin.android-oss_8.3.99.186_amd64.deb && dpkg -i xamarin.android-oss_8.3.99.186_amd64.deb
      - run:
          name: nuget
          command: nuget restore Xamarin_Calculator.sln
      - run:
          name: xamarin
          command: msbuild Xamarin_Calculator.sln
      
          
