version: 2
jobs:
  build:
    docker:
      - image: mono
    steps:
      - checkout
      - run:
          name: nuget
          command: nuget restore Xamarin_Calculator.sln
      - run:
          name: xamarin
          command: msbuild Xamarin_Calculator.sln
      
          
