version: 2
jobs:
  build:
    docker:
      - image: mono
    steps:
      - checkout
      - run:
          name: xamarin
          command:mono nuget.exe restore
          command: msbuild Xamarin_Calculator.sln
